### ISSUE TITLE
Updated examples

### ISSUE THREAD

**Issue by ev1stensberg** [badosa/JSON-stat#10]
Hi! Sorry for the disturbance! I'm doing some work in stat now, and the  documentation is really scattered. This toolkit is great, and includes a lot of great engineering, but using node and json-stat isn't really covered in examples. I'd like to see something like an example using modern javascript and node in order to convert json-stat to data-structures you could output. The closest thing I've come to this is doing something like in the screenshot, but some of the examples are also outdated, when it comes to transpiling and using webpack, though this is a special use case. 

This is the closest thing I've come to extract the data in Node, but as showed in the tonic-dev example, using got fails, due internal errors in babel. If you know a fix to this, I'd very much like to see that! 

![skjermbilde 2016-08-19 kl 14 33 52](https://cloud.githubusercontent.com/assets/16735925/17809903/fb0baf28-6619-11e6-9b10-8ad14250cf4e.png)

**Comment by ev1stensberg** [comment]
Also, some picky stuff around expressions and arrow functions. They should be left like resp => resp.json() inline :)

**Comment by ev1stensberg** [comment]
Right now, this is what I get, but there's a lot of mixed documentation about how to extract the data.


![skjermbilde 2016-08-19 kl 14 38 08](https://cloud.githubusercontent.com/assets/16735925/17809998/aabf2a94-661a-11e6-9393-b1a1ca728336.png)

**Comment by badosa** [comment]
Check the [wiki](https://github.com/badosa/JSON-stat/wiki) for documentation, particularly, the [API Reference](https://github.com/badosa/JSON-stat/wiki/API-Reference) section.

If you managed to read bundle 66000 from Statistics Norway into an object, you'll need to read it with the JSON-stat Javascript Toolkit (_JSONstat(obj)_), select the first and only dataset in the bundle (_Dataset(0)_) and probably convert it into an array of objects (_toTable({type: "arrobj"})_).

`JSONstat(obj).Dataset(0).toTable({type: "arrobj"})`
