### ISSUE TITLE
Publish JJUS to npm

### ISSUE THREAD

**Issue by jfsiii** [badosa/JSON-stat#13]
While you can `require('jsonstat')`, JJUS still must be loaded by a `<script>` tag, as far as I can tell.

Please publish the utils file to npm as well. Be sure to `require('jsonstat')` in that file and list `jsonstat` as a dependency in `package.json`

**Comment by jfsiii** [comment]
> I never thought JJUS as a module but more as a bundle of different high level helper functions, some of them (tbrowser) they even require a browser and a DOM.

There are many "high-level helper function" packages on npm.  `npm` isn't just for `node` modules. Even before [bower became deprecated](https://github.com/bower/bower/issues/2298)
![screen shot 2017-05-25 at 10 19 16 am](https://cloud.githubusercontent.com/assets/57655/26461956/bf46abf0-4133-11e7-970c-5cd21ae17428.png) `npm` was a great way to publish modules.

Putting JJUS on `npm` allows us to install and import it like all the rest of our dependencies.

>Would it make sense to you to also add some of the functionality of JJUS to jsonstat-conv (Command line tools for converting JSON-stat documents)? Things like:
>
>jsonstat2jsonstat (to support join())
>arrobj2jsonstat
>csv2jsonstat

That sounds like a nice addition. Especially in light of #6

**Comment by badosa** [comment]
> a bundle of different high level helper functions

What I also meant by this is that JJUS was a way for me to offer in a bundle some unrelated JSON-stat code that I had been using for demos and examples and that I thought it might be useful to share. What actually triggered the publication of JJUS was the discovery that not up-to-date code from old examples of the table browser had been copied and were in used in several sites.

The fact that this code was originally developed for demos and examples explains why there wasn't a focus on performance: its main goal was to show that a particular functionality was doable in JSON-stat. That was specially true of join(): this method was a way to try to start a discussion on what sort of merges made sense. Which explains [issue #14](https://github.com/badosa/JSON-stat/issues/14).

It probably makes sense to face issue #14 first before publishing JJUS on npm.

**Comment by badosa** [comment]
As [issue #14](https://github.com/badosa/JSON-stat/issues/14) is probably not trivial, I decided to publish JJUS on npm as it is.

`npm install jsonstat-utils`

`tbrowser` has been removed from the npm version.
