### ISSUE TITLE
Investigate join-by performance

### ISSUE THREAD

**Issue by jfsiii** [badosa/JSON-stat#14]
I ran into an issue recently where `merged = JSONstatUtils.join(datasets, {by: 'date'})` took 3500-5000 milliseconds (3.5 - 5 seconds) on an array of 30 values.

I was able to work around this in our particular case using the following:

```
var meta = datasets[0];
var parts = [meta].concat(datasets);
var merged = JSONstatUtils.join(parts);
var keyIndex = meta.id.indexOf(key);
var values = datasets.reduce(function(acc, dataset) {
	return acc.concat(dataset.dimension[key].category.index                             
}, []);

merged.dimension[key].category.index = values;
merged.size[keyIndex] = values.length;
```

This took 3.5 to 5 _milliseconds_ or 1/1000th the time of the original approach.

While I recognize this solution is specific to our data shape, and not suitable for all valid values, I think it highlights opportunities for optimizations in `join`.

I'll follow up with a trace showing where the time is spent but I believe it was in the repeated calls to `toTable`.

<details>
 <summary>Example dataset entry</summary>
<pre>
{
  "value": [128,13111,65683,87994,88140,101251,104489,101686,97839,84065,72174,62909,55400,48720,43354,39239,35373,31809,29476,26521,24325,22810,20810,19187,18266,16528,15594,14517,13850,12930,11931,11359,10607,10055,9421,8971,8511,7920,7771,7097,6819,6828,6312,6076,5704,5710,5315,5052,4875,4666,4509,4463,4309,3954,3819,3689,3593,3495,3342,3150,3125,3017,2940,2823,2766,2633,2624,2515,2401,2387,2291,2246,2119,2019,1997,1939,1998,1826,1953,1963,1873,1978,1898,1777,1791,1707,1740,1762,1640,1621,1493,1483,1422,1382,1340,1337,1298,1230,1178,1199,1179,1103,1139,1031,1084,1062,978,1037,960,944,904,973,927,883,816,895,838,881,828,770,737,791,775,768,717,725,697,652,658,632,656,616,599,599,550,590,554,527,519,516,522,474,500,524,493,470,449,499,493,463,442,451,404,391,451,403,408,429,494,726,533,684,651,504,482,472,456,439,373,371,345,347,327,315,299,291,311,312,331,287,293,261,275,292,252,261,256,270,249,256,255,223,239,243,233,224,201,249,279,317,231,291,267,239,210,205,173,180,188,212,167,173,190,179,186,188,184,147,177,156,172,151,183,209,193,221,234,190,184,152,173,144,147,171,154,168,138,140,132,130,137,140,145,147,131,145,121,150,137,131,107,135,114,119,115,125,111,123,129,155,109,108,115,118,127,133,113,121,97,120,104,115,123,124,118,117,107,117,123,129,124,96,101,108,111,71,94,97,104,120,99,101,105,90,106,113,107,98,80,98,107,113,95,98,88,88,93,82,109,81,101,96,72,97,109,88,92,103,89,91,112,94,114,104,110,94,79,105,99,109,96,90,83,78,81,88,78,91,89,65,76,77,70,69,80,92,92,76,100,77,76,81,77,64,69,78,70,70,73,88,67,72,59,61,66,61,78,63,58,67,59,62,75,63,66,50,62,63,56,73,63,59,67,70,62,60,69,59,72,66,62,51,46,63,53,50,47,59,46,48,59,65,77,55,63,59,48,65,54,53,52,46,49,50,52,54,53,46,63,37,53,58,50,42,47,44,50,41,53,28,53,42,40,32,46,57,47,36,31,46,38,49,37,51,46,45,38,44,47,33,39,56,36,40,45,40,44,33,40,45,37,38,48,44,60,39,47,39,32,42,31,43,34,42,36,24,25,40,30,42,32,33,43,46,34,45,40,35,37,30,37,37,34,31,39,45,56,65,59,44,39,42,29,36,29,22,34,42,32,37,41,35,36,31,25,21,25,27,42,28,22,31,32,32,34,34,30,24,24,19,25,25,25,22,31,25,33,27,28,22,18,20,29,26,42,27,29,19,26,24,31,12,26,21,26,24,29,15,30,20,38,28,20,24,32,40,28,28,53,38,33,25,26,42,21,30,28,16,29,35,28,21,37,29,28,24,19,21,20,34,28,26,22,28,17,15,17,17,20,22,17,29,16,19,24,18,14,15,25,10,16,21,17,10,21,14,18,16,22,10,26,8,28,21,18,9,16,18,12,16,20,19,13,13,12,14,21,18,12,23,13,12,21,23,22,20,22,13,21,20,18,24,39,23,14,21,20,14,10,16,17,20,19,17,11,19,12,14,14,17,15,13,14,14,13,14,18,17,14,21,17,13,15,17,14,17,29,13,18,30,18,17,16,14,18,16,17,15,17,16,14,32,16,9,13,9,8,16,10,13,11,14,9,18,13,16,20,14,8,15,12,10,18,12,22,8,12,22,11,13,15,11,14,10,11,10,8,19,9,16,12,15,15,8,12,8,9,11,20,11,15,14,16,16,9,16,10,17,11,14,0],
  "label": "Example latency values",
  "id": ["date","metric","client","country","bin"],
  "dimension": {
    "date": {
      "label": "Date",
      "category": { "index": [ "2017-04-22T00:00:00Z" ] }
    },
    "metric": {
      "label": "Metric",
      "category": {
        "index": [ "Latency" ],
        "unit": {
          "Latency": {
            "label": "Milliseconds",
            "decimals": 0
          }
        }
      }
    },
    "client": {
      "label": "Client",
      "category": { "index": [ "android" ] }
    },
    "country": {
      "label": "Country",
      "category": { "index": [ "All" ]
      }
    },
    "bin": {
      "label": "Bin",
      "category": {
        "index": ["0","250","500","750","1000","1250","1500","1750","2000","2250","2500","2750","3000","3250","3500","3750","4000","4250","4500","4750","5000","5250","5500","5750","6000","6250","6500","6750","7000","7250","7500","7750","8000","8250","8500","8750","9000","9250","9500","9750","10000","10250","10500","10750","11000","11250","11500","11750","12000","12250","12500","12750","13000","13250","13500","13750","14000","14250","14500","14750","15000","15250","15500","15750","16000","16250","16500","16750","17000","17250","17500","17750","18000","18250","18500","18750","19000","19250","19500","19750","20000","20250","20500","20750","21000","21250","21500","21750","22000","22250","22500","22750","23000","23250","23500","23750","24000","24250","24500","24750","25000","25250","25500","25750","26000","26250","26500","26750","27000","27250","27500","27750","28000","28250","28500","28750","29000","29250","29500","29750","30000","30250","30500","30750","31000","31250","31500","31750","32000","32250","32500","32750","33000","33250","33500","33750","34000","34250","34500","34750","35000","35250","35500","35750","36000","36250","36500","36750","37000","37250","37500","37750","38000","38250","38500","38750","39000","39250","39500","39750","40000","40250","40500","40750","41000","41250","41500","41750","42000","42250","42500","42750","43000","43250","43500","43750","44000","44250","44500","44750","45000","45250","45500","45750","46000","46250","46500","46750","47000","47250","47500","47750","48000","48250","48500","48750","49000","49250","49500","49750","50000","50250","50500","50750","51000","51250","51500","51750","52000","52250","52500","52750","53000","53250","53500","53750","54000","54250","54500","54750","55000","55250","55500","55750","56000","56250","56500","56750","57000","57250","57500","57750","58000","58250","58500","58750","59000","59250","59500","59750","60000","60250","60500","60750","61000","61250","61500","61750","62000","62250","62500","62750","63000","63250","63500","63750","64000","64250","64500","64750","65000","65250","65500","65750","66000","66250","66500","66750","67000","67250","67500","67750","68000","68250","68500","68750","69000","69250","69500","69750","70000","70250","70500","70750","71000","71250","71500","71750","72000","72250","72500","72750","73000","73250","73500","73750","74000","74250","74500","74750","75000","75250","75500","75750","76000","76250","76500","76750","77000","77250","77500","77750","78000","78250","78500","78750","79000","79250","79500","79750","80000","80250","80500","80750","81000","81250","81500","81750","82000","82250","82500","82750","83000","83250","83500","83750","84000","84250","84500","84750","85000","85250","85500","85750","86000","86250","86500","86750","87000","87250","87500","87750","88000","88250","88500","88750","89000","89250","89500","89750","90000","90250","90500","90750","91000","91250","91500","91750","92000","92250","92500","92750","93000","93250","93500","93750","94000","94250","94500","94750","95000","95250","95500","95750","96000","96250","96500","96750","97000","97250","97500","97750","98000","98250","98500","98750","99000","99250","99500","99750","100000","100250","100500","100750","101000","101250","101500","101750","102000","102250","102500","102750","103000","103250","103500","103750","104000","104250","104500","104750","105000","105250","105500","105750","106000","106250","106500","106750","107000","107250","107500","107750","108000","108250","108500","108750","109000","109250","109500","109750","110000","110250","110500","110750","111000","111250","111500","111750","112000","112250","112500","112750","113000","113250","113500","113750","114000","114250","114500","114750","115000","115250","115500","115750","116000","116250","116500","116750","117000","117250","117500","117750","118000","118250","118500","118750","119000","119250","119500","119750","120000","120250","120500","120750","121000","121250","121500","121750","122000","122250","122500","122750","123000","123250","123500","123750","124000","124250","124500","124750","125000","125250","125500","125750","126000","126250","126500","126750","127000","127250","127500","127750","128000","128250","128500","128750","129000","129250","129500","129750","130000","130250","130500","130750","131000","131250","131500","131750","132000","132250","132500","132750","133000","133250","133500","133750","134000","134250","134500","134750","135000","135250","135500","135750","136000","136250","136500","136750","137000","137250","137500","137750","138000","138250","138500","138750","139000","139250","139500","139750","140000","140250","140500","140750","141000","141250","141500","141750","142000","142250","142500","142750","143000","143250","143500","143750","144000","144250","144500","144750","145000","145250","145500","145750","146000","146250","146500","146750","147000","147250","147500","147750","148000","148250","148500","148750","149000","149250","149500","149750","150000","150250","150500","150750","151000","151250","151500","151750","152000","152250","152500","152750","153000","153250","153500","153750","154000","154250","154500","154750","155000","155250","155500","155750","156000","156250","156500","156750","157000","157250","157500","157750","158000","158250","158500","158750","159000","159250","159500","159750","160000","160250","160500","160750","161000","161250","161500","161750","162000","162250","162500","162750","163000","163250","163500","163750","164000","164250","164500","164750","165000","165250","165500","165750","166000","166250","166500","166750","167000","167250","167500","167750","168000","168250","168500","168750","169000","169250","169500","169750","170000","170250","170500","170750","171000","171250","171500","171750","172000","172250","172500","172750","173000","173250","173500","173750","174000","174250","174500","174750","175000","175250","175500","175750","176000","176250","176500","176750","177000","177250","177500","177750","178000","178250","178500","178750","179000","179250","179500","179750","180000","180250","180500","180750","181000","181250","181500","181750","182000","182250","182500","182750","183000","183250","183500","183750","184000","184250","184500","184750","185000","185250","185500","185750","186000","186250","186500","186750","187000","187250","187500","187750","188000","188250","188500","188750","189000","189250","189500","189750","190000"]
      }
    }
  },
  "size": [ 1, 1, 1, 1, 761 ],
  "role": {
    "metric": [ "metric" ],
    "time": [ "date" ],
    "geo": [ "country" ]
  },
  "version": "2.0",
  "class": "dataset"
}
</pre>
</details>

**Comment by jfsiii** [comment]
I am glad to look into this, but am not familiar with the various valid forms of values that should be supported.

If you publish tests showing some examples, I can take a crack at tuning the function.

**Comment by jfsiii** [comment]
Here are two screenshots from the trace. 

<img width="1265" alt="screen shot 2017-05-29 at 9 44 56 pm" src="https://cloud.githubusercontent.com/assets/57655/26568458/60408710-44b8-11e7-91a3-11b5aed0ea88.png">
<img width="1277" alt="screen shot 2017-05-29 at 9 46 25 pm" src="https://cloud.githubusercontent.com/assets/57655/26568459/6453907c-44b8-11e7-9330-7d74ee2657b5.png">

The code I'm profiling is

```
const merged = JSONstatUtils.join(datasets, { by: 'date', label: meta.label });
```

where `datasets` is an array of 30 entries like the one in the issue description.

Note that there are 50 calls to `toTable` and many of the calls are 100-200ms

**Comment by badosa** [comment]
@jfsiii Thank you very much for looking into this. For generalization's sake, `join` relies on `toTable` and `fromTable`. So yes, in a dataset join by dimension (like your example) you need at least as many `toTable` as datasets (in your example, 30 datasets of around 800 values each: total 24000 values).

That might not be the most efficient solution but it's probably one of the simplest ones because normalization is taken care by `toTable`.

The issue can be tried to be solved using a different approach (avoiding `toTable` altogether) or improving `toTable`. The first solution requires modifying [JJUS](https://github.com/badosa/JSON-stat/tree/master/utils;), the second, [JJT](https://github.com/badosa/JSON-stat). Something that has to be taken into account is that JJT was born many years ago and was originally designed to be compatible with very old browsers with no suport for ES5, which explains why the use of the "new" array methods (Array.indexOf, Array.forEach, Array.filter, Array.map, etc.) was included very recently (and very sparingly). Which means there might be room for improvement in JJT too.

> I am glad to look into this, but am not familiar with the various valid forms of values that should be supported.

I understand the second solution does not require this familiarity. And, in the first one, the various valid forms can be avoided if instead of dealing with the original objects you deal with the jsonstat instance produced by `JSONstat()` using the JJT methods. This last approach seems preferable to make sure the solution is forward compatible with future additions.

The official samples are available here:

https://json-stat.org/samples/

**Comment by badosa** [comment]
Issue closed because repository has been frozen (new version is at https://github.com/jsonstat/toolkit).
