### ISSUE TITLE
Problem converting json-stat to table

### ISSUE THREAD

**Issue by predicador37** [badosa/JSON-stat#16]
Hi @badosa:

I'm not sure if this is a bug, maybe I'm doing something wrong.

I'm trying to use jsonstat library installed from npm to convert a JSON-stat file to a table.

This is the file I'm using: https://gist.github.com/predicador37/0c2bbfd821268d1a9bfd12be83e36e9d

And the code I'm trying:

        let bundle = JSONstat(response.data)
        console.log(bundle.Dataset(0).toTable())

At the console, Year and Month dimensions appear as 'undefined'. The rest of values are correctly populated. I think the file is json-stat 2 compliant...

Could you give me a hand?

Thanks in advance!

**Comment by predicador37** [comment]
I'll answer myself.. it seems the JSON file has an ilegal character ('-') in the name of a dimension. I'll try with the name fixed and update my "maybe-not-an-issue".

Don't bother looking at it...

**Comment by predicador37** [comment]
OK, new update. The JSON-stat file is 2.0 compliant. But Year and Month dimensions appear undefined.

It can be checked in the viewer:

https://json-stat.org/format/viewer/?uri=http%3A%2F%2Fwww.icane.es%2Fdata%2Fapi%2Fcpi-base-2016-ecoicop-general-group-index.json-stat%3Fs%3D%255Bdim4_d.dim4_h%255Df%253B%255Bdim3_d.dim3_h%255Df%253B%255Bdim2_d.dim2_h%255Dc%253D%255B%25C3%258Dndice%2520general%255D%253B%255BMeasures%255Dc%253D%255Bvariacion_anual%255D

any ideas?

**Comment by trygu** [comment]
Seems like you have empty labels on "mes" and "ano". 

`        "mes": {
            "label": "Mes",
            "category": {
                "index": {
                    "10": 9,
                    "11": 10,
                    "12": 11,
                    "01": 0,
                    "02": 1,
                    "03": 2,
                    "04": 3,
                    "05": 4,
                    "06": 5,
                    "07": 6,
                    "08": 7,
                    "09": 8
                },
                **"label": {}**
            }
        },`

**Comment by trygu** [comment]
This seems to work: https://gist.githubusercontent.com/trygu/00a4bc9c629f0140352554283298dc58/raw/be57a4e36887aa9e740222cb07f600e47f6ab116/cpi-base-2016.json

**Comment by predicador37** [comment]
Indeed, that's the problem.

Thanks a lot, @trygu 

This was not an issue then.

**Comment by badosa** [comment]
According to the spec [label](https://json-stat.org/format/#label) is optional. But when specified 

> When it is a child of category, it is an object where the keys are the category IDs and the values are the labels.

Translation: you don't need to provide _label_ but, if you do, category IDs must be included as properties: the label object cannot be empty.

Thank you @trygu for spotting the error so quickly!

**Comment by badosa** [comment]
BTW, the @predicador37 example passes the [JSON-stat Validator](https://json-stat.org/format/validator/). Meaning, I must update the JSON-stat schemas. I'll try to do that tonight.

**Comment by predicador37** [comment]
Well, I'm glad my wrong usage can be of help to improve the validator, at least :smile:
