### ISSUE TITLE
How to have metadata for values

### ISSUE THREAD

**Issue by ashkan2200** [badosa/JSON-stat#18]
Hi all,
This is more of a question than a bug.
I have a jsonstat data structure where for one of the value columns in the table form I would like to place numbers from 0 to 3. Each number has a specific meaning. For instance 0=Neutral, 1=For, 2=Against . This is not a dimension so I can not give it an index and label.

Is there a way to attach metadata to one of the value columns. From the documentation I see that I can attach a status to each value but that is not exactly the best way. I know what values I would have in this column. I just don't want to place the names as the value.

If there is a better way, please give an example on how one can do it.

Thank you,
Best,
Ashkan

**Comment by badosa** [comment]
You can use [extension](https://json-stat.org/format/#extension) for that. In fact, Eurostat uses it for a similar scenario (describing the different standard status codes they use).
