### ISSUE TITLE
slice: how to query on multiple values ?

### ISSUE THREAD

**Issue by prabuvenkat** [badosa/JSON-stat#20]
For example -- 
```
JSONstat( this ).Slice(
    { "year": ["2010", "2011", "2012"] }
)
```

Or, is there any other way to achieve this ?

**Comment by badosa** [comment]
Selecting several categories of a dimension is not supported by Slice() (technically, it wouldn't be a slice).

But you probably could get the same results using [toTable()](https://github.com/badosa/JSON-stat/wiki/API-Reference#totable) with a callback.
