### ISSUE TITLE
How to write json-stat?

### ISSUE THREAD

**Issue by moxious** [badosa/JSON-stat#6]
I like the json-stat idea, and the library looks workable.   I read the entire [slideshare](http://www.slideshare.net/badosa/json-stat) and now I'm onboard.   

OK, so how to I actually **write** JSON-stat instances?  Suppose I'm a back-end developer, and I have all kind of time series data that I'd like to send to the front in json-stat format.  Categories and dimensions?  Sold!   

I'm having trouble finding any info online about how to write json-stat instances other than example files, and the schema documentation itself.  Is there any library to facilitate this?   In particular, if I'm going to write an array of values into a json-stat instance, I have to solve the "flattening" problem and do my own math based on my dimensions and concepts, of which value should be in which cell.  The slideshare gives me enough detail to let me embark on this, but given Eurostat and other example JSON-stat files, someone must have already done this, and packaged it into library form, right?

Docs on the front page of this repo and in the wiki are good for reading JSON-stat, but how are people creating that data in the first place?

**Comment by badosa** [comment]
I'm probably not the best person to answer your question (maybe Lars from
Norway?). That said, I think flattening is not the problem (unflattening
is), but providing the metadata in the right order.

X.

**Comment by moxious** [comment]
It makes sense that a library isn't going to be able to do everything for you in writing json-stat (like choosing metadata ordering); but you'd think that in trivial cases (turning tables with row/columns into json-stat with no additional dimensions) there'd already be something there, right?

**Comment by badosa** [comment]
Could you post your questions to the JSON-stat Google Group?

https://groups.google.com/forum/#!forum/json-stat

**Comment by jfsiii** [comment]
@moxious I [posted this question to the group](https://groups.google.com/forum/#!topic/json-stat/JwAJgTzClJw)
