### ISSUE TITLE
Dimension response support

### ISSUE THREAD

**Issue by cgoessen** [badosa/JSON-stat#8]
Hi, according to the format spec, I'd like to use dimension response with the Json stat js toolkit.
But currently it fails since it assumes dimension is never the root document.

I've created a pull request (https://github.com/badosa/JSON-stat/pull/7) to fix that (but I don't know what minyfier you are using so only the max.js is modified).

Hope it helps.

**Comment by badosa** [comment]
True, JJT does not support dimension responses. It wasn't a priority considering no data provider is so far offering dimension responses and has shown an interest in doing so. But it was in my to-do list.

Let me some time to review your request.

**Comment by badosa** [comment]
Done: version 0.12.0 of JJT supports dimension responses.
